Diplom/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from Diplom import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tutorapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorapp/urls.py
from django.urls import path#импортирует функцию `path` из модуля `django.urls`, которая используется для определения маршрутов URL в Django.
from . import views#импортирует модуль `views.py`, в котором содержатся функции обработки запросов.

app_name = 'tutorapp'#задает пространство имен для URL-шаблонов этого приложения. Это позволяет ссылаться на URL-шаблоны из этого приложения в шаблонах и функциях `reverse()` Django.

urlpatterns = [#Это определяет список URL-шаблонов для этого Django приложения.
    path('', views.welcome, name='welcome'),  # заменили 'main' на 'welcome' пользователь переходит по этому URL, вызывается функция `welcome` из `views.py`.
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('main/', views.main, name='main'),# добавили новый маршрут для главной страницы
    path('api/tutor/<int:tutor_id>/', views.tutor_detail_api, name='tutor_detail_api'),
    path('student_dashboard/', views.student_dashboard, name='student_dashboard'),
    path('tutor_dashboard/', views.tutor_dashboard, name='tutor_dashboard'),
    path('accept_request/<str:student_name>/<str:subject_name>/', views.accept_request, name='accept_request'),
    path('decline_request/<str:student_name>/<str:subject_name>/', views.decline_request, name='decline_request'),
    path('homework/create/<int:lesson_id>/', views.create_homework, name='create_homework'),
    path('homework/<int:homework_id>/', views.homework_page, name='homework_page'),
    path('check_homework/<int:pk>', views.check_homework, name='check_homework'),
    path('update_avatar/', views.update_avatar, name='update_avatar'),
]
#`name=...`: Это имена URL-шаблонов, которые можно использовать для ссылки на эти URL из шаблонов и функций `reverse()` Django.
#определяют другие URL-шаблоны. Первый аргумент каждой функции `path` - это шаблон URL. Второй аргумент - функция обработчика, которая вызывается, когда пользователь переходит по соответствующему URL.
# Некоторые из этих URL-шаблонов используют переменные (например, `<int:tutor_id>`, `<str:student_name>`, `<int:lesson_id>` и т.д.), которые извлекаются из URL и передаются в функцию обработчика.

templates/Main.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Личный аккаунт</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
    <header>
        <div class="header-content">
            <h1>Мой сайт</h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'tutorapp:main' %}">Главная</a></li>
                        {% if user.tutor %}
                            <li><a href="{% url 'tutorapp:tutor_dashboard' %}">Личный кабинет</a></li>
                        {% endif %}
                        {% if user.student %}
                            <li><a href="{% url 'tutorapp:student_dashboard' %}">Личный кабинет</a></li>
                        {% endif %}
                        <li><a href="{% url 'tutorapp:logout' %}">Выйти</a></li>
                    {% else %}
                        <li><a href="{% url 'tutorapp:login' %}">Войти</a></li>
                        <li><a href="{% url 'tutorapp:register' %}">Зарегистрироваться</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>

    <div class="main">

        <div class="settings-outer">
            <div class="settings">
                <h2>Фильтры поиска:</h2>
                <form method="POST">
                    {% csrf_token %}
                    <p><label>Предмет: </label>{{ form.subject }}</p>
                    <p><label>Максимальная цена: </label> {{ form.price }}</p>
                        {% for choice in form.days_of_week %}
                            <div class="checkbox-div">
                                <label for="{{ choice.id_for_label }}">{{ choice.choice_label }}</label>
                                {{ choice.tag }}
                                <input type="time" name="start_time_{{choice.id_for_label}}" class="start-time" style="visibility: hidden;">
                                <input type="time" name="end_time_{{choice.id_for_label}}" class="end-time" style="visibility: hidden;">
                            </div>
                        {% endfor %}
                    <button type="submit" name="filter_button">Применить фильтры</button>
                </form>
            </div>
        </div>

        <div class="mini-card-container">
            {% for tutor in tutors %}
            <div class="mini-card" data-id="{{ tutor.id }}" onclick="showCard(this.getAttribute('data-id'))">
                <div class="mini-avatar-name">
                    {% if tutor.avatar %}
                        <img src="{{ tutor.avatar.url }}" class="mini-avatar">
                    {% else %}
                        <img src="{% static 'avatar.jpg' %}" class="mini-avatar">
                    {% endif %}
                    <h3>{{ tutor.name }}</h3>
                </div>
                <p class="mini-description">{{ tutor.bio }}</p>
                <div class="price-enroll">
                    <p class="price">{{ tutor.hourly_rate }} руб.</p>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="overlay" id="overlay" style="display: none;">
            <div class="card-container" id="card-container">
                <div class="card">
                    <div id="tutorContent">
                        <div class="avatar">
                            <img class="avatar" id="avatar">
                        </div>
                        <div class="info">
                            <h2 id="tutor-name"></h2>
                            <p id="tutor-email"></p>
                            <p id="tutor-age"></p>
                            <p id="tutor-phone"></p>
                            <p id="tutor-subject"></p>
                            <p id="tutor-hourly_rate:"></p>
                            <p id="tutor-qualification"></p>
                            <p id="tutor-bio"></p>
                        </div>
                        <div class="card-buttons">
                            <button class="card-button" id="enrollButton">Записаться</button>
                        </div>
                    </div>
                    <!-- Форма записи к репетитору -->
                    <div id="enrollForm" style="display: none;">
                        <h2>Форма записи</h2>
                        <form id="enrollment_form" method="POST" class="enrollment_form">
                            {% csrf_token %}
                            <p>{{ enrollment_form.start_date.label_tag }} {{ enrollment_form.start_date }}</p>
                            <p>{{ enrollment_form.end_date.label_tag }} {{ enrollment_form.end_date }}</p>
                            <p>{{ enrollment_form.days_of_week.label_tag }}</p>
                            {% for choice in enrollment_form.days_of_week %}
                                <div class="checkbox">
                                    <label for="{{ choice.id_for_label }}">{{ choice.choice_label }}</label>
                                    {{ choice.tag }}
                                    <input type="time" name="start_{{choice.id_for_label}}" class="start" style="visibility: hidden;">
                                    <input type="number" name="duration_{{choice.id_for_label}}" class="duration" style="visibility: hidden;">
                                </div>
                            {% endfor %}
                            <input type="hidden" id="tutor_id" name="tutor_id">
                            <button type="submit" name="enrollment_button" class="settings button">Отправить заявку</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}




    </div>

    <footer>
        <div class="footer-content">
            <p>© 2023 Мой сайт</p>
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'main.js' %}"></script>

</body>
</html>

templates/Welcome.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Приветственная страница</title>
    <link rel="stylesheet" href="{% static 'welcome.css' %}">
</head>
<body>
    <header>
        <div class="header-content">
            <h1>Добро пожаловать на наш сайт</h1>
        </div>
    </header>

    <div class="main">
        <img src="{% static 'welcome.png' %}" alt="Welcome image" class="welcome-image">
        <h2>Почему стоит выбрать наш сайт?</h2>
        <p>
            Мы предлагаем удобный и быстрый способ найти подходящего репетитора для вас. Настройте фильтры под себя и найдите своего идеального репетитора уже сейчас!
        </p>
        <a href="/main/" class="main-button">Перейти на главную страницу</a>
    </div>

    <footer>
        <div class="footer-content">
            <p>© 2023 Мой сайт</p>
        </div>
    </footer>
</body>
</html>

templates/create_homework.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Homework</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <style>
        /* CSS here */
        body {
            font-family: 'Arial', sans-serif;
            background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
            background-size: 400% 400%;
            animation: gradient-background 15s ease-in-out infinite;
            color: #eee;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 2em;
            box-sizing: border-box;
            display: grid;
            grid-gap: 2em;
        }

        .task, .btn {
            background-color: transparent;
            border: none;
            transition: all 0.3s ease;
            margin-bottom: 2em;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            border-radius: 10px;
            box-shadow: 0px 10px 15px rgba(0, 0, 0, 0.1);
            word-wrap: break-word;
        }

        .task:hover, .btn:hover {
            transform: scale(1.02);
            box-shadow: 0px 20px 30px rgba(0, 0, 0, 0.2);
        }

        h4.task-number {
            color: #fff;
            font-size: 1.3em;
            margin-bottom: 1em;
            transition: all 0.3s ease;
            max-width: 500px;
            word-wrap: break-word;
        }

        h4.task-number:hover {
            color: #23d5ab;
        }

        textarea {
            border-radius: 5px;
            transition: all 0.3s ease;
            padding: 5px;
            overflow: hidden; /* hide scrollbar */
            resize: none; /* prevent manual resize */
            min-height: 40px; /* initial minimum height */
        }

        textarea:focus {
            border-color: #1d815c;
            box-shadow: 0 0 5px lightgrey;
            outline: none;
        }

        @keyframes gradient-background {
            0% { background-position: 0% 50%; }
            50% { background-position: 100% 50%; }
            100% { background-position: 0% 50%; }
        }

        .form-group{
            width: 700px;
        }

    </style>
</head>
<body>

    <div class="container">
        <h2>Конструктор домашнего задания</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div id="tasks-container">
                <!-- The first task will be displayed immediately -->
                <div class="task">
                    <h4 class="task-number">Задание 1</h4>
                    <div class="form-group">
                        <label for="id_task_0_exercise">Упражнение:</label>
                        <textarea name="task_0_exercise" id="id_task_0_exercise" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="id_task_0_answer">Ответ:</label>
                        <textarea name="task_0_answer" id="id_task_0_answer" class="form-control"></textarea>
                    </div>
                    <button type="button" class="btn btn-danger remove-task">Удалить задание</button>
                </div>
                <!-- Other tasks will be added here -->
            </div>
            <button type="button" class="btn btn-primary" id="add-task">Добавить задание</button>
            <button type="submit" class="btn btn-success">Сохранить</button>
        </form>
    </div>

    <!-- Task Template -->
    <div class="task" style="display: none;">
        <h4 class="task-number">Задание 2</h4>
        <div class="form-group">
            <label for="id_task_0_exercise">Упражнение:</label>
            <textarea name="task_0_exercise" id="id_task_0_exercise" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label for="id_task_0_answer">Ответ:</label>
            <textarea name="task_0_answer" id="id_task_0_answer" class="form-control"></textarea>
        </div>
        <button type="button" class="btn btn-danger remove-task">Удалить задание</button>
    </div>

    <script src="{% static 'create_homework.js' %}"></script>

    <script>
        // Auto resize textarea on input
        $('textarea').on('input', function () {
            this.style.height = 'auto';
            this.style.height = (this.scrollHeight) + 'px';
        });
    </script>


</body>
</html>

templates/homework_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Домашнее задание</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
            background-size: 400% 400%;
            animation: gradient-background 15s ease-in-out infinite;
            color: #eee;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 2em;
            box-sizing: border-box;
            display: grid;
            grid-gap: 2em;
        }

        .card{
            background-color: transparent;
            border: none;
            transition: all 0.3s ease;
            margin-bottom: 2em;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            border-radius: 10px;
            box-shadow: 0px 10px 15px rgba(0, 0, 0, 0.1);
            word-wrap: break-word;
        }

        .card:hover {
            transform: scale(1.02);
            box-shadow: 0px 20px 30px rgba(0, 0, 0, 0.2);
        }

        .btn {
            background-color: transparent;
            border: none;
            transition: all 0.3s ease;
            margin-bottom: 2em;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            border-radius: 10px;
            box-shadow: 0px 10px 15px rgba(0, 0, 0, 0.1);
            word-wrap: break-word;
        }

        .btn:hover {
            background-color: transparent;
            transform: scale(1.02);
            box-shadow: 0px 20px 30px rgba(0, 0, 0, 0.2);
        }

        h5.card-title {
            color: #fff;
            font-size: 1.3em;
            margin-bottom: 1em;
            transition: all 0.3s ease;
            max-width: 500px;
            word-wrap: break-word;
        }

        h5.card-title:hover {
            color: #23d5ab;
        }

        textarea {
            border-radius: 5px;
            transition: all 0.3s ease;
            padding: 5px;
            overflow: hidden; /* hide scrollbar */
            resize: none; /* prevent manual resize */
            min-height: 40px; /* initial minimum height */
        }

        textarea:focus {
            border-color: #1d815c;
            box-shadow: 0 0 5px lightgrey;
            outline: none;
        }

        @keyframes gradient-background {
            0% { background-position: 0% 50%; }
            50% { background-position: 100% 50%; }
            100% { background-position: 0% 50%; }
        }

    </style>

</head>
<body class="bg-light">
    <div class="container py-5">
        <h2 class="mb-4">Домашнее задание</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for task in tasks %}
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ task.exercise }}</h5>
                        <div class="form-group">
                            <label for="task_answer_{{ task.id }}">Ваш ответ:</label>
                            <textarea name="task_answer_{{ task.id }}" id="task_answer_{{ task.id }}" class="form-control"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="task_file_{{ task.id }}">Прикрепить файл:</label>
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="task_file_{{ task.id }}" name="task_file_{{ task.id }}">
                                <label class="custom-file-label" for="task_file_{{ task.id }}">Выберите файл</label>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success mt-3">Сохранить</button>
        </form>
    </div>
    <script>
        // Update the name of the file in the custom file input
        $(".custom-file-input").on("change", function() {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });

        // Auto resize textarea on input
        $('textarea').on('input', function () {
            this.style.height = 'auto';
            this.style.height = (this.scrollHeight) + 'px';
        });

    </script>
</body>
</html>

templates/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Личный аккаунт</title>
    <link rel="stylesheet" href="{% static 'login.css' %}">
</head>
<body>
  <div class="login-container lef-card">
    <div class="login-header">
      <h2>Вход</h2>
    </div>
    <form method="post" class="login-form">
      {% csrf_token %}
      <div class="form-field">
        {{ form.username.label_tag }}
        {{ form.username }}
      </div>
      <div class="form-field">
        {{ form.password.label_tag }}
        {{ form.password }}
      </div>
      <button type="submit" class="login-button">Login</button>
    </form>
  </div>
</body>
</html>

templates/register.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
    <link rel="stylesheet" href="{% static 'register.css' %}">
</head>
<body>
  <div class="register-container">
    <div class="register-header">
      <h2>Регистрация</h2>
    </div>
    <form method="post" class="register-form" id="register-form" novalidate>
      {% csrf_token %}
      <div class="form-field">
        {{ form.username.label_tag }}
        {{ form.username }}
        <div class="validation-message" id="username-validation"></div>
      </div>
      <div class="form-field">
        {{ form.email.label_tag }}
        {{ form.email }}
        <div class="validation-message" id="email-validation"></div>
      </div>
      <div class="form-field">
        {{ form.password1.label_tag }}
        {{ form.password1 }}
        <div class="validation-message" id="password1-validation"></div>
      </div>
      <div class="form-field">
        {{ form.password2.label_tag }}
        {{ form.password2 }}
        <div class="validation-message" id="password2-validation"></div>
      </div>
      <div class="form-field">
        {{ form.is_tutor.label_tag }}
        {{ form.is_tutor }}
      </div>
      <button type="submit" class="register-button">Регистрация</button>
    </form>
  </div>
  <script>
    window.onload = function() {
      const form = document.getElementById('register-form');

      form.addEventListener('input', function(event) {
        const target = event.target;
        if (target.nodeName.toLowerCase() !== 'input') return;

        const validationMessage = target.parentNode.querySelector('.validation-message');
        if (target.validity.valid) {
          hideValidationMessage(validationMessage);
        } else if (target.validity.valueMissing) {
          displayValidationMessage(validationMessage, 'Пожалуйста, заполните это поле.');
        } else if (target.validity.patternMismatch) {
          displayValidationMessage(validationMessage, target.title);
        }

        if (target.name === 'password2') {
          const password1 = document.querySelector('input[name="password1"]');
          if (target.value !== password1.value) {
            displayValidationMessage(validationMessage, 'Пароли не совпадают');
          } else {
            hideValidationMessage(validationMessage);
          }
        }
      });

      form.addEventListener('focusin', function(event) { // event triggered when an input field is in focus
        const target = event.target;
        if (target.nodeName.toLowerCase() !== 'input') return;

        const validationMessage = target.parentNode.querySelector('.validation-message');
        if (!target.validity.valid) {
          if (target.validity.valueMissing) {
            displayValidationMessage(validationMessage, 'Пожалуйста, заполните это поле.');
          } else if (target.validity.patternMismatch) {
            displayValidationMessage(validationMessage, target.title);
          }
        }

        if (target.name === 'password2') {
          const password1 = document.querySelector('input[name="password1"]');
          if (target.value !== password1.value) {
            displayValidationMessage(validationMessage, 'Пароли не совпадают');
          }
        }
      });

      form.addEventListener('focusout', function(event) { // event triggered when an input field loses focus
        const target = event.target;
        if (target.nodeName.toLowerCase() !== 'input') return;
        const validationMessage = target.parentNode.querySelector('.validation-message');
        hideValidationMessage(validationMessage);
      });

      form.addEventListener('submit', function(event) {
        const inputs = form.querySelectorAll('input');
        let hasError = false;

        inputs.forEach(function(input) {
          const validationMessage = input.parentNode.querySelector('.validation-message');
          if (!input.validity.valid) {
            if (input.validity.valueMissing) {
              displayValidationMessage(validationMessage, 'Пожалуйста, заполните это поле.');
            } else if (input.validity.patternMismatch) {
              displayValidationMessage(validationMessage, input.title);
            }
            hasError = true;
          } else {
            hideValidationMessage(validationMessage);
          }
        });

        const password1 = document.querySelector('input[name="password1"]');
        const password2 = document.querySelector('input[name="password2"]');
        const passwordValidationMessage = document.getElementById('password2-validation');
        if (password1.value !== password2.value) {
          displayValidationMessage(passwordValidationMessage, 'Пароли не совпадают');
          hasError = true;
        } else {
          hideValidationMessage(passwordValidationMessage);
        }

        if (hasError) {
          event.preventDefault();
        }
      });

      function displayValidationMessage(element, message) {
        element.textContent = message;
        element.classList.add('show');
      }

      function hideValidationMessage(element) {
        element.textContent = '';
        element.classList.remove('show');
      }
    };

  </script>
</body>
</html>